spring.application.name=tresorbackend

#variables can be overwritten by environment variables
spring.datasource.url=jdbc:mariadb://localhost:3306/tresordb
spring.datasource.username=root
spring.datasource.password=1234
ENCRYPTION_SECRET=LikeAPro
google.recaptcha.secret=6Ld2FzgrAAAAAF1vN_me0bzKDp9VYlJSzvd9JQ18

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

CROSS_ORIGIN=http://localhost:3000